### ISSUE TITLE
Don't work with Pydio 8.0.1

### ISSUE THREAD

**Issue by omvillegas** [squarou/pydio-mailer.phpmailer-smtp#3]
I have an instance of Pydio 8.0.1, and i try to install this plugin on it. I put it on my plugins directory and activate it, But when i go to the mail settings i can't see the option on the Mail plugin configurator

**Comment by squarou** [comment]
The plugin is working fine with 8.0.3 for me... Didn't notice any pb with 8.0.3
Maybe clearing the plugin cache may be helpful
